# ArgoCD Application (GitOps) - vervang repoURL en path
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fk-webstack
  namespace: argocd
spec:
  project: default
  source:
    # TODO: vervang door jouw Git repo
    repoURL: https://github.com/your-user/your-repo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: fk-webstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
