# MongoDB Service (cluster internal)
apiVersion: v1
kind: Service
metadata:
  name: fk-mongodb
  namespace: fk-webstack
spec:
  selector:
    app: fk-mongodb
  ports:
    - port: 27017
      targetPort: 27017
