# Service for frontend (internal)
apiVersion: v1
kind: Service
metadata:
  name: fk-frontend
  namespace: fk-webstack
spec:
  selector:
    app: fk-frontend
  ports:
    - port: 80
      targetPort: 80
