# Self-Signed Certificate Issuer (for local testing)
# Don't give extra points but shows HTTPS
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fk-selfsigned
spec:
  selfSigned: {}
