# ArgoCD Application (GitOps)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fk-webstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/F85K/fk-webserver.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: fk-webstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
